'use strict';
// Turns the validated params object into files Godot can actually load.
//
// The GDD (§4.1, §4.4) makes one rule structural: every tunable lives in
// config/game_params.tres and nothing is hardcoded anywhere in the codebase. So the crew's
// headline artifact is not a report about the numbers — it is the resource file itself,
// plus the script that gives it a type. Deterministic scaffolding; no model involved.

// GDScript types a Dictionary value by how it is written, so `5` is an int and `5.0` is a
// float — and `heat / passes` on two ints does integer division. Every physics value must
// therefore carry a decimal point even when it is a whole number. Only genuine counts stay
// integers, identified by their key.
const COUNT_KEY = /(slots|tier|count|weight|passes)/;
const COUNT_PARENT = new Set(['optimal_pass_count']);

function isCount(key, parentKey) {
  if (parentKey && COUNT_PARENT.has(parentKey)) return true;
  return typeof key === 'string' && COUNT_KEY.test(key);
}

function num(value, key, parentKey) {
  if (!Number.isInteger(value)) return String(value);
  return isCount(key, parentKey) ? String(value) : `${value}.0`;
}

// A JS value as a Godot literal. Godot's Dictionary/Array syntax is close enough to JSON
// that the only real work is quoting and float formatting.
function lit(value, indent = 0, key = null, parentKey = null) {
  const pad = '\t'.repeat(indent);
  const padIn = '\t'.repeat(indent + 1);

  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return num(value, key, parentKey);
  if (typeof value === 'string') return JSON.stringify(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => `${padIn}${lit(v, indent + 1, key, parentKey)}`).join(',\n');
    return `[\n${items}\n${pad}]`;
  }

  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  const body = entries
    .map(([k, v]) => `${padIn}${JSON.stringify(k)}: ${lit(v, indent + 1, k, key)}`)
    .join(',\n');
  return `{\n${body}\n${pad}}`;
}

const GROUPS = ['flight', 'cargo', 'reentry', 'ablation', 'landing', 'tow_fee', 'eva', 'economy'];

// The companion script. Without it a .tres has nowhere to hang custom properties, so the
// two files ship together and the resource is loadable the moment the Godot project exists.
function emitScript() {
  const exports = GROUPS.map(
    (g) => `@export var ${g}: Dictionary = {}`
  ).join('\n');

  return `# Generated by the Junkstronaut tuning crew. Do not hand-edit.
#
# Regenerate with:  node crew/run-crew.js
#
# Every tunable value in the game lives in the resource that uses this script
# (config/game_params.tres). GDD §4.4: hardcoded literals elsewhere in the codebase are a
# rejection condition, because they force the next session to read code it should not need.
class_name GameParams
extends Resource

${exports}
@export var upgrades: Array = []
@export var debris: Array = []

## Value of one piece of debris, before landing grade and tow fee.
func debris_value(entry: Dictionary) -> float:
\tvar base: float = economy["size_class_base_value"][entry["size_class"]]
\tvar band_mult: float = economy["band_value_multiplier"][entry["band"]]
\tvar value: float = base * band_mult
\tif entry.get("fragile", false):
\t\tvalue *= float(economy["fragile_value_premium"])
\treturn value

## Tow fee as a fraction of haul value. GDD §2.3.3: zero inside the free radius, linear
## beyond it, clamped at max_fee_fraction, never negative.
func tow_fee_fraction(distance_m: float, half_circumference_m: float) -> float:
\tvar free: float = tow_fee["free_radius_m"]
\tif distance_m <= free:
\t\treturn 0.0
\tvar span: float = max(half_circumference_m - free, 1.0)
\tvar t: float = clampf((distance_m - free) / span, 0.0, 1.0)
\treturn t * float(tow_fee["max_fee_fraction"])
`;
}

function emitResource(params, catalog) {
  const lines = [
    '[gd_resource type="Resource" script_class="GameParams" load_steps=2 format=3]',
    '',
    '[ext_resource type="Script" path="res://config/game_params.gd" id="1_gameparams"]',
    '',
    '[resource]',
    'script = ExtResource("1_gameparams")',
  ];

  for (const g of GROUPS) {
    if (params[g] !== undefined) lines.push(`${g} = ${lit(params[g])}`);
  }
  lines.push(`upgrades = ${lit(params.upgrades || [])}`);

  // The catalog rides in the same resource on purpose: the game needs debris and their
  // prices together, and one file is the whole point of §4.4.
  const debris = (catalog && catalog.debris ? catalog.debris : []).map((d) => ({
    id: d.id,
    display_name: d.display_name,
    band: d.band,
    size_class: d.size_class,
    fragile: d.fragile,
    mass_kg: d.mass_kg,
    spawn_weight: d.spawn_weight,
    slots_crushed: catalog.size_classes[d.size_class].slots_crushed,
    slots_uncrushed: catalog.size_classes[d.size_class].slots_uncrushed,
    hand_tetherable: catalog.size_classes[d.size_class].hand_tetherable,
  }));
  lines.push(`debris = ${lit(debris)}`);

  return lines.join('\n') + '\n';
}

module.exports = { emitResource, emitScript, lit };
