'use strict';
module.exports = {
  agent: 'economy-balancer',
  flight: {
    dry_mass_kg: 108,
    fuel_capacity_kg: 360,
    thrust_n: 7000,
    fuel_burn_kgs: 2,
    rcs_thrust_n: 300,
    rcs_fuel_burn_kgs: 0.05,
    rotation_rate_degs: 90,
  },
  cargo: { base_slots: 6, compactor_tier: 1 },
  reentry: {
    heat_capacity: 232,
    heat_dissipation_s: 5,
    cargo_damage_interval_s: 3,
    commit_floor_m: 8000,
    unstaged_heat_multiplier: 3,
    off_retrograde_penalty: 1,
  },
  ablation: {
    cycle_toll_base_pct: 5,
    cycle_toll_growth: 1.9,
    heat_cost_coefficient: 0.000007,
    heat_cost_exponent: 3,
    skim_peak: 67,
    skim_heat_multiplier: [1, 0.377, 0.377, 0.377],
    heat_index: { bottom: 100, middle: 129.5, top: 169.1 },
    cost_curve: {
      bottom: [12.0, 16.98, 37.14, 73.54],
      middle: [20.2, 17.42, 37.58, 73.98],
      top: [38.85, 18.42, 38.57, 74.97],
    },
    plate_capacity_pct: 100,
    optimal_skims: { bottom: 0, middle: 1, top: 1 },
  },
  landing: {
    soft_landing_ms: 5,
    damage_per_ms_over: 6,
    no_gear_multiplier: 2,
    fragile_multiplier: 2,
    parachute_area_m2: 85,
    parachute_drag_coefficient: 1.5,
    descent_speed_full_hold_ms: 4.61,
  },
  tow_fee: { free_radius_m: 1200, max_fee_fraction: 0.5, curve: 'linear' },
  eva: {
    suit_mass_kg: 110,
    jetpack_thrust_n: 240,
    jetpack_fuel_kg: 18,
    jetpack_burn_kgs: 0.35,
    base_tether_slots: 2,
    magnet_hold_force_n: 900,
    magnet_range_screens: 0.125,
    latch_jerk_coefficient: 1,
    swing_jerk_coefficient: 1,
  },
  economy: {
    launch_cost: 95,
    replate_cost_per_pct: 2,
    repair_cost_per_pct: 5,
    value_gradient: { at_bottom: 1, at_top: 5.5 },
    size_class_base_value: { small: 40, medium: 90, oversized: 320 },
    fragile_value_premium: 3,
  },
  upgrades: [
    { part: 'fuel_tank', tier: 1, cost: 350, effect: 'fuel_capacity_kg', value: 460 },
    { part: 'fuel_tank', tier: 2, cost: 900, effect: 'fuel_capacity_kg', value: 560 },
    { part: 'thruster', tier: 1, cost: 400, effect: 'thrust_n', value: 8500 },
    { part: 'thruster', tier: 2, cost: 1000, effect: 'thrust_n', value: 10000 },
    { part: 'storage', tier: 1, cost: 600, effect: 'base_slots', value: 8 },
    { part: 'storage', tier: 2, cost: 1500, effect: 'base_slots', value: 10 },
    { part: 'heat_shield', tier: 1, cost: 500, effect: 'heat_capacity', value: 235 },
    { part: 'heat_shield', tier: 2, cost: 1300, effect: 'heat_capacity', value: 238 },
    { part: 'parachute', tier: 1, cost: 300, effect: 'parachute_area_m2', value: 105 },
    { part: 'parachute', tier: 2, cost: 800, effect: 'parachute_area_m2', value: 125 },
    { part: 'hand_magnet', tier: 1, cost: 250, effect: 'magnet_hold_force_n', value: 1400 },
    { part: 'hand_magnet', tier: 2, cost: 700, effect: 'magnet_hold_force_n', value: 2000 },
  ],
  balance_notes: ['placeholder placeholder placeholder'],
};
