'use strict';
// The Economy Balancer's candidate for revision pass 2.
module.exports = {
  agent: 'economy-balancer',
  flight: {
    dry_mass_kg: 1146,
    fuel_capacity_kg: 3820,
    thrust_n: 74200,
    fuel_burn_kgs: 21.2,
    rcs_thrust_n: 3180,
    rcs_fuel_burn_kgs: 0.53,
    rotation_rate_degs: 90,
  },
  cargo: { base_slots: 6, compactor_tier: 1 },
  reentry: {
    heat_capacity: 208,
    heat_dissipation_s: 5,
    cargo_damage_interval_s: 3,
    commit_floor_m: 8000,
    unstaged_heat_multiplier: 3,
    off_retrograde_penalty: 1,
  },
  ablation: {
    cycle_toll_base_pct: 5,
    cycle_toll_growth: 1.9,
    heat_cost_coefficient: 0.000007,
    heat_cost_exponent: 3,
    skim_peak: 41.6,
    skim_heat_multiplier: [1, 0.74, 0.419, 0.419],
    heat_index: { bottom: 100, middle: 125.3, top: 160.7 },
    cost_curve: {
      bottom: [12.0, 17.84, 34.07, 68.87],
      middle: [18.77, 20.58, 34.57, 69.37],
      top: [34.05, 26.78, 35.69, 70.49],
    },
    plate_capacity_pct: 100,
    optimal_skims: { bottom: 0, middle: 0, top: 1 },
  },
  landing: {
    soft_landing_ms: 5,
    damage_per_ms_over: 6,
    no_gear_multiplier: 2,
    fragile_multiplier: 2,
    parachute_area_m2: 870,
    parachute_drag_coefficient: 1.5,
    descent_speed_full_hold_ms: 4.59,
  },
  tow_fee: { free_radius_m: 1200, max_fee_fraction: 0.5, curve: 'linear' },
  eva: {
    suit_mass_kg: 110,
    jetpack_thrust_n: 520,
    jetpack_fuel_kg: 18,
    jetpack_burn_kgs: 0.35,
    base_tether_slots: 2,
    magnet_hold_force_n: 900,
    magnet_range_screens: 0.125,
    latch_jerk_coefficient: 1,
    swing_jerk_coefficient: 1,
  },
  economy: {
    launch_cost: 95,
    replate_cost_per_pct: 2,
    repair_cost_per_pct: 5,
    value_gradient: { at_bottom: 1, at_top: 5.5 },
    size_class_base_value: { small: 40, medium: 90, oversized: 320 },
    fragile_value_premium: 3,
  },
  upgrades: [
    { part: 'fuel_tank', tier: 1, cost: 350, effect: 'fuel_capacity_kg', value: 4880 },
    { part: 'fuel_tank', tier: 2, cost: 900, effect: 'fuel_capacity_kg', value: 5940 },
    { part: 'thruster', tier: 1, cost: 400, effect: 'thrust_n', value: 90200 },
    { part: 'thruster', tier: 2, cost: 1000, effect: 'thrust_n', value: 106100 },
    { part: 'storage', tier: 1, cost: 600, effect: 'base_slots', value: 8 },
    { part: 'storage', tier: 2, cost: 1500, effect: 'base_slots', value: 10 },
    { part: 'heat_shield', tier: 1, cost: 500, effect: 'heat_capacity', value: 213 },
    { part: 'heat_shield', tier: 2, cost: 1300, effect: 'heat_capacity', value: 218 },
    { part: 'parachute', tier: 1, cost: 300, effect: 'parachute_area_m2', value: 1075 },
    { part: 'parachute', tier: 2, cost: 800, effect: 'parachute_area_m2', value: 1280 },
    { part: 'hand_magnet', tier: 1, cost: 250, effect: 'magnet_hold_force_n', value: 1400 },
    { part: 'hand_magnet', tier: 2, cost: 700, effect: 'magnet_hold_force_n', value: 2000 },
  ],
  balance_notes: ['placeholder'],
  catalog_concerns: [],
};
